config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'memos/index'
  root to: "memos#index"
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo_user.rb
class MemoUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :memo_users
  has_many :users, through: :memo_users
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         validates :name, presence: true
         has_many :memo_users
         has_many :rooms, through: :memo_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def new
    @room = Room.new
  end
  def create
      @room = Room.new(room_params)
      if @room.save
        redirect_to root_path
      else
        render :new
      end
    end
    private
    def room_params
      params.require(:room).permit(:name, user_ids: [])
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end
  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/_main_memo.html.erb
<div class="memo-header">
    <div class="memo-header1">
        <div class="memo-title">
          買い物
        </div>
    </div>
   <div class="memo-header2">
      <div class="header-button">
        
        <%= link_to "新規メモ作成", new_room_path %>
      </div>
     </div>
    <div class="memo-header3">
      <div class="header-button">
        <a href="#">メモをやめる</a>
      </div>
   </div>
</div>

<div class="memos">
<div class="memo">
    <div class="upper-memo">
      <div class="memo-user">
        Tom
      </div>
      <div class="memo-date">
        2020/3/31(Wed) 12:43:30
      </div>
    </div>
    <div class="lower-memo">
      <div class="memo-content">
        マヨネーズ
      </div>
    </div>
  </div>

  <div class="memo">
    <div class="upper-memo">
      <div class="memo-user">
        Tom
      </div>
      <div class="memo-date">
        2020/3/31(Wed) 12:47:30
      </div>
    </div>
    <div class="lower-memo">
      <div class="memo-content">
       七味
      </div>
    </div>
  </div>
</div>

<div class="form">
<div class="form-input">
    <input class="form-message" placeholder= "文字を入力してください">
    <label class="form-image">
      <span class="image-file">画像</span>
      <input type="file" class="hidden">
    </label>
  </div>
  <input class="form-submit" type="submit" value="送信">
</div>

app/views/memos/_side_bar.html.erb
<div class="side-bar-header">
  <div class="user-name">
      <%= link_to current_user.name, edit_user_path(current_user) %>
  </div>
  <div class="log_out">
      <%= link_to "log_out", destroy_user_session_path, method: :delete, class: 'btn'%>
  </div>
</div>

<div class="memo_lists">
  <% current_user.rooms.each do |room| %>
    <div class="room">
      <div class="memo-name">
        <a href="#"><%= room.name %></a>
      </div>
    </div>
  <% end %>
</div>

app/views/memos/index.html.erb
<div class="wrapper">
  <div class="side_bar">
    <%= render "side_bar" %>
  </div>
  <div class="memo_side">
    <%= render "main_memo" %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%=form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
      <select name="room[user_ids][]">
          <option value="">チャットするユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
      </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>